version: '3.8'
services:
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localhost:8000"
      AWS_REGION: "localhost"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
