org: willsmithte
app: aws-node-express-dynamodb-api
service: aws-node-express-dynamodb-api
frameworkVersion: '3'

custom:
  usersTableName: 'shred-crew-users-${sls:stage}'
  resortsTableName: 'shred-crew-resort-${sls:stage}'
  skiSessionsTableName: 'shred-crew-sessions-${sls:stage}'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !Sub '${ResortsTable.Arn}/*'
            - Fn::GetAtt: [ ResortsTable, Arn ]
            - !Sub '${UsersTable.Arn}/*'
            - Fn::GetAtt: [ UsersTable, Arn ]
            - !Sub '${SkiSessionsTable.Arn}/*'
            - Fn::GetAtt: [ SkiSessionsTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    RESORTS_TABLE: ${self:custom.resortsTableName}
    SKI_SESSIONS_TABLE: ${self:custom.skiSessionsTableName}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: '*'

resources:
  - ${file(db/users.yml)}
  - ${file(db/resorts.yml)}
  - ${file(db/ski-sessions.yml)}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dynamodb-seed

package:
  patterns:
    - '!.dynamodb/**'
    - '!./db/bootstrap/resorts.json'
