org: willsmithte
app: aws-node-express-dynamodb-api
service: aws-node-express-dynamodb-api
frameworkVersion: '3'

custom:
  usersTableName: 'users-${sls:stage}'
  resortsTableName: 'resorts-${sls:stage}'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    RESORTS_TABLE: ${self:custom.resortsTableName}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.usersTableName}
    ResortsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.resortsTableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dynamodb-seed

package:
  patterns:
    - '!.dynamodb/**'
    - './db/bootstrap/resorts.json'
