Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi2
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: loginType
              KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: loginType
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.usersTableName}
