Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: email
              KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.usersTableName}
